### PR TITLE
Update README.md for information on monthly meetings

### PR DESCRIPTION
**Pull request by sleepypioneer**
Add section on who attends the council monthly meetings and remove the part around requesting to attend.

### CODE REVIEW

**Comment by sleepypioneer** [comment]
@trallard tagging you for review :)

**Review by trallard — APPROVED** [review]
Thanks for your contribution ☺️ I think this will go a long way to avoid confusion. I will approve and let @BethanyG have another look as I know she also wanted to get the README squared up.

**Comment by trallard** [comment]
In the spirit of moving this forward I will go ahead and merge, and we can adjust wording later if needed. 
Thanks @sleepypioneer

**Comment by BethanyG** [comment]
Thank you @trallard  -- was coming here to do exactly that!  Apologies for the delay in reviewing.  😄

**Comment by trallard** [comment]
Not a problem figured you have your hands full with the website stuff so thought I'd merge it before I forgot.

**Pull request merged**
